In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import (
    datasets, metrics, model_selection as skms, neighbors
)

In [3]:
dataset = datasets.load_diabetes()

In [9]:
# fitting a 5-fold cv with sklearn.
model = neighbors.KNeighborsRegressor(n_neighbors=10)
skms.cross_val_score(model, dataset.data, dataset.target, cv=5, scoring="neg_mean_squared_error")

array([-3206.7541573 , -3426.43134831, -3587.94215909, -3039.49443182,
       -3282.60159091])

In [11]:
# experimenting with stratification.
dataset = datasets.load_iris()
model = neighbors.KNeighborsClassifier(n_neighbors=10)
skms.cross_val_score(model, dataset.data, dataset.target, cv=5)

array([0.96666667, 1.        , 1.        , 0.93333333, 1.        ])

In [24]:
# not stratified
pet = np.array(["cat", "dog", "cat", "dog", "dog", "dog"])
list_folds = list(skms.KFold(2).split(pet))
training_indexes = np.array(list_folds)[:, 0, :]
print(pet[training_indexes])

[['dog' 'dog' 'dog']
 ['cat' 'dog' 'cat']]


In [18]:
# stratified
pet = np.array(["cat", "dog", "cat", "dog", "dog", "dog"])
indexes = np.array(list(skms.StratifiedKFold(2).split(np.ones_like(pet), pet)))
training_indexes = indexes[:, 0, :]
print(pet[training_indexes])

[['cat' 'dog' 'dog']
 ['cat' 'dog' 'dog']]


In [23]:
# running non stratified CV.
dataset = datasets.load_iris()
model = neighbors.KNeighborsClassifier(10)
non_strat_kf = skms.KFold(5)
skms.cross_val_score(model, dataset.data, dataset.target, cv=non_strat_kf)

array([1.        , 1.        , 0.86666667, 0.96666667, 0.76666667])