In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
oned_vec = np.arange(5)
oned_vec, np.dot(oned_vec, oned_vec)

(array([0, 1, 2, 3, 4]), 30)

In [12]:
row_vec = np.arange(5).reshape(1, 5)
col_vec = np.arange(0, 50, 10).reshape(5, 1)
row_vec, col_vec, np.dot(row_vec, col_vec), np.dot(col_vec, row_vec)

(array([[0, 1, 2, 3, 4]]),
 array([[ 0],
        [10],
        [20],
        [30],
        [40]]),
 array([[300]]),
 array([[  0,   0,   0,   0,   0],
        [  0,  10,  20,  30,  40],
        [  0,  20,  40,  60,  80],
        [  0,  30,  60,  90, 120],
        [  0,  40,  80, 120, 160]]))

In [15]:
col_vec = np.arange(0, 50, 10).reshape(5, 1)
row_vec = np.arange(0, 5).reshape(1, 5)
col_vec, row_vec

(array([[ 0],
        [10],
        [20],
        [30],
        [40]]),
 array([[0, 1, 2, 3, 4]]))

In [17]:
oned_vec = np.arange(5)
oned_vec

array([0, 1, 2, 3, 4])

In [19]:
np.dot(oned_vec, col_vec)

array([300])

In [21]:
oned_vec.shape, col_vec.shape

((5,), (5, 1))

In [24]:
numbers = np.arange(5)
numbers.shape

(5,)

In [26]:
# transposing the above 1D array
numbers.T

array([0, 1, 2, 3, 4])

In [31]:
numbers_2d = np.arange(0, 50, 10).reshape(5, 1)
numbers_2d

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [33]:
# using the np.allclose function which takes in three parameters, the first element, the second element, and the third is the tolerance element which could be wither the relative tolerance or the absolute tolerance.
(1.1 + 2.2 == 3.3)
# this above prints as false, but
np.allclose(1.1 + 2.2, 3.3)
# this returns as true, why
# because using the allclose function accepts the value as long as it is in the tolerance limit, if not used, specifically when adding floating point numbers, the machine epsilon can cause some errors.
# machine epsilon is the smallest value that can be added to 1, without actually changing its value. Machine epsilon plays an important role in the addition of floating point numbers, if the difference between two floating point numbers is less than machine epsilon then these two numbers are considered to be equal.


True